### ISSUE TITLE
Week 01 - Day 2 - Expanding your world

### ISSUE THREAD

**Issue by mdewey** [evixamar/assignments#2]
# Expanding Your World

In this assignment, you will end up with a simple styled web page, published on the web.

Create a new website that shows some basic styling and formatting using HTML and CSS. This website should help share some information for one of your favorite hobbies.

## Objectives

- Practice using your tools text editor
- Explore new CSS properties
- Publish a web page

## Requirements

- Have `git`, `hub`, and `node` installed. We should have done this together in class.

### Explorer Mode

- [ ] Follow all of the setup instructions (See "Assignment Setup").
- [ ] Create a new `app-app` project.
- [ ] Using CSS, style your page to imitate some of the classic designs of the web. Feel free to make this look as "bad" as you want. Here are some sites to gain inspiration:
  - [10 90s websites designs you won’t believe existed](https://www.justinmind.com/blog/10-90s-websites-designs-you-wont-believe-existed/)
- [ ] Add a second page about your hobby with (at least) 2 pictures and with other facts about your hobby.
- [ ] Add a menu to your site so a user can go back and forth between the new pages.
- [ ] Between the 2 pages, use at least 5 tag selectors, 5 id selectors, and 5 class selectors to style content on your page.
- [ ] Deploy your site.

### Adventure Mode

- [ ] use pseudo-classes to style elements when you hover the mouse over them
- [ ] Add a third page, that has a table. Create this table to have alternating colored rows and a hover over color.
- [ ] Make a nav bar that sticks to the top of the page (see the nav bar here for example - https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes)
- [ ] Make a footer that always sticks to the bottom of the page

### Epic Mode

- [ ] Explore CSS animations and add some life to your static page. Feel free to really dig into these and try to animate all elements on your page to some extent

### CSS

- [Cool game to learn CSS selectors](https://flukeout.github.io/)
- [Introduction to CSS](https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS)
- [Getting Started with CSS Rules](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/CSS_basics#Anatomy_of_a_CSS_ruleset)
- [All the CSS properties](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference#Keyword_index)
- [pseudo-classes and pseudo-elements](https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS/Pseudo-classes_and_pseudo-elements)
- [http://www.csszengarden.com/](http://www.csszengarden.com/)

### HTML

- [HTML Tags](https://developer.mozilla.org/en-US/Learn/HTML/HTML_tags)
- [Evolution of the Web](http://www.evolutionoftheweb.com)

## Reading Material

To prep for tomorrow's lesson, you can [read about flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/).

**Comment by evixamar** [comment]
!DOCTYPE html>
<html>
	<head lang="en">
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<title>MyHobbies</title>
		<link rel="shortcut icon" href="/favicon.ico" />
		<link rel="stylesheet" href="/screen.css" />
		<body>
			<h1>My Hobbies</h1>

			<p>
				Anyone who’s done boxing training will tell you this is one of the
				hardest of hardcore workouts there is – incredible cardio, strength,
				endurance, and coordination. Muay Thai is the hottest boxing style
				around, so there’s never been a better time to take it up.
				<img src="/images/hobbies-boxing.jpg" alt="boxing pic" />
			</p>
			<h1 class="hobbies">My myHobbies</h1>
			Learn To Play An Instrument: It’s one of the most commonly cited
			activities for helping increase IQ. And there’s evidence that playing
			music changes the structure and function of the brain, with parts of your
			grey matter that control memory, hearing and motor skills becoming more
			active. Plus, playing ‘Sweet Child Of Mine’ on the accordion is quite the
			party piece. <img src="/images/hobbies-guitar.jpg" alt="playing the guitar" />
		</body>
	
  </p>
</h1 class="hobbies">myhobbies></h1>
Take Photographs -Without Your Phone
It seems like a thing of the past – a lost analog art, if you like – but there are still impressive film cameras available to buy. Old-school cameras are still superior in natural light for authentic-looking photographs. Plus, by having to get it right, you skip all the time you spend dropping filters or fiddling in post-production apps on your phone. You have to be in the moment. 
<img src="/images/best-hobbies-for-men1.jpg" alt=Picture photography />
</head>p>
<h1 class="hobbies">myHobbies</h1>
In this video curtesy of W3 school, you will see nature at its best in Alaska. -EMV-
<video width="320" height="240" controls>
  <source src="/images/movie.mp4" alt="video/mp4"> />

**Comment by evixamar** [comment]
https://hobbies-evixamar.netlify.com

Please let me know if you have any questions.

**Comment by evixamar** [comment]
https://hobbies-evixamar.netlify.com

Please let me know if you have any questions.

**Comment by mdewey** [comment]
Please submit to me the GitHub repository so I can see your code.

**Comment by evixamar** [comment]
https://github.com/evixamar/assignments/issues/2

Please let me know if you have any questions

**Comment by mdewey** [comment]
Please submit to me the GitHub repository so I can see your code.

This should look something like this: 

http://www.github.com/evixamar/my-hobbies. 

Let me know if you still need help

**Comment by mdewey** [comment]
Your homework was marked: **Acceptable**

![Not Bad](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBDdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--26e47afe0d88e75d27a696b1e3719f5c026a93c5/not-bad.gif)
> &ldquo;Not Bad&rdquo;
__&mdash; via **[Jason L Perry](https://gifs.suncoast.io/venerations/6)**__
