### ISSUE TITLE
Week 06 - Day 3 - Choose your own API Adventure

### ISSUE THREAD

**Issue by mdewey** [evixamar/assignments#21]
# Choose your own API Adventure

In this assignment, you'll build a front end for an API of your choice

## Objectives

- Reinforce component architecture in React
- Reinforce reading of API documentation (some are great, and some are terrible)
- Creating and designing your own features for a web app

## Requirements

We're going to build a front end for an API of your choice. Choose one from [this list](https://github.com/toddmotto/public-apis)

_NOTE_ You'll need to choose one with `Auth` being `No` or `apiKey` since we haven't covered `OAuth` authentication yet.

_NOTE_ You'll also need to check to see if the API will work from your browser. You can do a quick check by making a small `create-react-app`, doing an `axios.get` or `fetch` of one API URL and see if you get browser errors.

### Explorer Mode

- [ ] Read your API docs
- [ ] Use Postman to make some API requests to be familiar with the API and the data it returns
- [ ] Create a list of the features you are going to create and how they will work
- [ ] Design your User Interface
- [ ] create-react-app
- [ ] Design your HTML statically in `App.js`
- [ ] Make it dynamic
- [ ] Use components when needed
- [ ] Deploy it and share it with friends

**Comment by evixamar** [comment]
https://github.com/evixamar/api-adventure

**Comment by mdewey** [comment]
The repository is there, but it looks like you are missing your commits. Make sure that your code is fully committed and push and then re-close the issue.

**Comment by evixamar** [comment]
https://github.com/evixamar/api-adventure

Mark, please review and advise. Thank you

**Comment by mdewey** [comment]
Still missing your latest commit, be sure to `git add . ` and `git commit -m "message here"` and `git push`

**Comment by evixamar** [comment]
Hello Mark,

I'm also looking at this one too, trying to figure out if you ever received it. Thanks

**Comment by evixamar** [comment]
https://github.com/evixamar/api-adventure

**Comment by mdewey** [comment]
Hello Manny! I don't see the latest version of your code. I only see what was generated by `app-app` . 

Remember for me to see your code on GitHub, you need to be committing your code. You should be following the directions here: https://suncoast.io/handbook/tools/assignment-turn-in

**Comment by evixamar** [comment]
Mark, Please review finished work. week 7 day 2

https://github.com/evixamar/api-adventure
