### ISSUE TITLE
Week 07 - Day 1 - INSERT INTO Student (knowledge) VALUES ('SQL')

### ISSUE THREAD

**Issue by gstark** [evixamar/assignments#23]
Every application uses data in some way. This will help you set up your development environment as well as get used to querying databases.

## Objectives

* Ensure our Postgres database is installed and working
* Create a database for Employees
* Write some queries to use the database

### Explorer Mode

* [ ] Create a database:
  - C#: called `CompanyDatabase`
  - Ruby: called `company_database`
* [ ] Create a table:
  - C#: named `Employees`
  - Ruby: named 'employees'
* [ ] Add the following columns to the table, Use your best judgement for data types
    - C#
      - Id (Primary Key)
      - FullName
      - Salary
      - Position
      - PhoneExtension
      - IsPartTime
    - Ruby
      - id (Primary Key)
      - full_name
      - salary
      - position
      - phone_extension
      - part_time
* [ ] Create queries that can do the following:
    - [ ] Select all columns for all employees
    - [ ] Select only the Full Name and Phone Extension for only Full Time employees
    - [ ] Insert a new part time employee, as a software developer, part time, with a salary of 450
    - [ ] Update all employees that are the cooks to have a salary of 500
    - [ ] Delete all employees that have the full name of "Lazy Lynn"
    - [ ] Update all employees to be full time
    - [ ] Add a column to the table
      - C#: called `ParkingSpotNumber` as a string that up to 10 characters long
      - Ruby: called `parking_spot_number` as a string that up to 10 characters long

* [ ] Turn in the above queries as a gist

### Adventure Mode

* [ ] Work on the Koans
* [ ] Work on your final project

### Epic Mode

* [ ] Investigate working with C#/Ruby and Postgres

## Additional Resources

* [https://www.postgresql.org/docs/10/static/index.html](https://www.postgresql.org/docs/10/static/index.html)

## Recommended Practice:

* For more practice, Hackerrank has a [SQL Track](https://www.hackerrank.com/domains/sql)

**Comment by evixamar** [comment]
CREATE TABLE departments (id SERIAL PRIMARY KEY, department_name VARCHAR(50))

CREATE TABLE

Time: 0.541s



=>Add a Foreign key named:

CompanyDatabase> ALTER TABLE employees ADD COLUMN DepartmentId INTEGER NULL

You're about to run a destructive command.

Do you want to proceed? (y/n): y

Your call!

ALTER TABLE

Time: 0.069s

CompanyDatabase> select * from Employees

+------+-----------------------------+------------+--------------------+------------------+-------| id   | fullname                    
                                     | salary     | position           | phoneextension   | ispart|------+-----------------------------+------------+--------------------+------------------+-------|   
| 1 Michael Tyson                    | $90,093.89 | Software Engineer  | 211              | False

| 2    | Mira Kang                   | $70,093.89 | Software Engineer  | 211              | False

| 3    | Tatiana                     | $70,093.89 | Software Engineer  | 211              | False

| 4    | Juanito                     | $80,093.89 | Software Engineer  | 211              | False

| 5    | Charlie                     | $80,093.89 | Software Engineer  | 211              | False

| 6    | Manny                       | $85,093.89 | Software Developer | 211              | False

| 8    | Carla                       | $500.00    | Cook               | 201              | False

| 9    | Maria                       | $500.00    | Cook               | 202              | False

| 10   | Joselin                     | $500.00    | Cook               | 203              | False

+------+-----------------------------+------------+--------------------+------------------+-------SELECT 9


+------+-----------------------------+------------+--------------------+------------------+--------------+---------------------+----------------+

| id   | fullname                    | salary     | position           | phoneextension   | isparttime   | parkingspotnumber   | departmentid   |

|------+-----------------------------+------------+--------------------+------------------+--------------+---------------------+----------------|

| 1    | Michael Tyson               | $70,093.89 | Software Engineer  | 211              | False        | <null>              | <null>         |

| 2    | Mira Kang                   | $70,093.89 | Software Engineer  | 211              | False        | <null>              | <null>         |

| 3    | Tatiana                     | $80,093.89 | Software Engineer  | 211              | False        | <null>              | <null>         |

| 4    | Juanito                     | $80,093.89 | Software Engineer  | 211              | False        | <null>              | <null>         |

| 5    | Charlie                     | $70,093.89 | Software Engineer  | 211              | False        | <null>              | <null>         |

| 6    | Manny                       | $85,093.89 | Software Developer | 211              | False        | <null>              | <null>         |

| 8    | Carla                       | $500.00    | Cook               | 201              | False        | <null>              | <null>         |

| 9    | Maria                       | $500.00    | Cook               | 202              | False        | <null>              | <null>         |

| 10   | Joselin                     | $500.00    | Cook               | 203              | False        | <null>              | <null>         |

+------+-----------------------------+------------+--------------------+------------------+--------------+---------------------+----------------+

SELECT 9



=>Add tables named:

Time: 0.005s

CompanyDatabase> CREATE TABLE Products(id SERIAL PRIMARY KEY, product_name v

 archar(50), price MONEY);

CREATE TABLE

Time: 0.043s

CompanyDatabase> select * from products

+------+----------------+---------+

| id   | product_name   | price   |

|------+----------------+---------|

+------+----------------+---------+

SELECT 0

Time: 0.008s

CompanyDatabase> CREATE TABLE orders(id SERIAL PRIMARY KEY, order_fecha date

 )

CREATE TABLE

Time: 0.061s

CompanyDatabase> select * from orders

+------+---------------+

| id   | order_fecha   |

|------+---------------|

+------+---------------+

SELECT 0

Time: 0.011s



=> In our company, 1 Order can have many Products and 1 Product can have many Orders. This will be a Many-to-Many relationship. Create the tables and foreign keys needed for this to happen

CompanyDatabase> CREATE TABLE products_orders(id SERIAL PRIMARY KEY, Product

 Id INTEGER NOT NULL, OrderId INTEGER NOT NULL)

CREATE TABLE

Time: 0.064s

CompanyDatabase> select * from products_orders

+------+-------------+-----------+

| id   | productid   | orderid   |

|------+-------------+-----------|

+------+-------------+-----------+

SELECT 0

Time: 0.007s



=> Given a department id, give me all employees in the department

CompanyDatabase> select * from employees where departmentid =5

+------+-----------------------------+------------+-------------------+------------------+--------------+---------------------+----------------+

| id   | fullname                    | salary     | position          | phoneextension   | isparttime   | parkingspotnumber   | departmentid   |

|------+-----------------------------+------------+-------------------+------------------+--------------+---------------------+----------------|

| 1    | Michael Tyson               | $90,093.89 | Software Engineer | 211              | False        | <null>              | 5              |

| 2    | Mira Kang                   | $90,093.89 | Software Engineer | 211              | False        | <null>              | 5              |

| 3    | Tatiana                     | $90,093.89 | Software Engineer | 211              | False        | <null>              | 5              |

| 4    | Juanito                     | $90,093.89 | Software Engineer | 211              | False        | <null>              | 5              |

| 5    | Charlie                     | $90,093.89 | Software Engineer | 211              | False        | <null>              | 5              |

+------+-----------------------------+------------+-------------------+------------------+--------------+---------------------+----------------+

SELECT 5

Time: 0.009s



=>Given a department name, give me the phone extensions

CompanyDatabase> select employees.phoneextension from employees join departments on employees.departmentid = departments.id where departments.department_name = 'Kitchen

 '

+------------------+

| phoneextension   |

|------------------|

| 201              |

| 202              |

| 203              |

+------------------+

SELECT 3

Time: 0.011s



=> Inserts a new product

CompanyDatabase> insert into products (product_name, price) values ('milk',1.25)

INSERT 0 1

Time: 0.015s

CompanyDatabase> insert into products (product_name, price) values ('1 dozen eggs',3.25)

INSERT 0 1

Time: 0.008s

CompanyDatabase> insert into products (product_name, price) values ('bread 16oz',2.99)

INSERT 0 1

Time: 0.011s

CompanyDatabase> insert into products (product_name, price) values ('tuna 8oz',3.99)

INSERT 0 1

Time: 0.009s

CompanyDatabase> insert into products (product_name, price) values ('sucar 8oz',1.99)

INSERT 0 1

Time: 0.027s

CompanyDatabase> select * from products

+------+----------------+---------+

| id   | product_name   | price   |

|------+----------------+---------|

| 1    | milk           | $1.25   |

| 2    | 10 dozen eggs   | $3.25   |

| 3    | bread 16oz     | $1.99   |

| 4    | tuna 8oz       | $3.99   |

| 5    | sugar 8oz      | $1.99   |

+------+----------------+---------+



=> Given an order id, display on the OrderNumber, and all the product names

CompanyDatabase> select o.ordernumber, p.product_name from products as p joi

 n products_orders as po  on p.id = po.productid join orders as o on po.orde

 rid = o.id where o.id = 1

+---------------+----------------+

| ordernumber   | product_name   |

|---------------+----------------|

| 334AL         | milk           |

+---------------+----------------+

SELECT 1

Time: 0.012s

CompanyDatabase>



=>Creates a new order

CompanyDatabase> insert into orders (order_fecha, ordernumber) values ('3/07 /2019','246GL')

INSERT 0 1

Time: 0.027s

CompanyDatabase> select * from orders

+------+---------------+---------------+

| id   | order_fecha   | ordernumber   |

|------+---------------+---------------|

| 1    | 2019-03-12    | 311AL         |

| 2    | 2019-03-11    | 325BL         |

| 3    | 2019-03-10    | 225ZL         |

| 4    | 2019-03-09    | 235ZL         |

| 5    | 2019-03-08    | 236GL         |

| 6    | 2019-03-07    | 246GL         |

+------+---------------+---------------+

SELECT 6

Time: 0.017s



=>Adds a product to an order

CompanyDatabase> insert into products_orders(productid,orderid,quantity) val ues(5,6,4)

INSERT 0 1

Time: 0.009s

CompanyDatabase> select * from products_orders

+------+-------------+-----------+------------+

| id   | productid   | orderid   | quantity   |

|------+-------------+-----------+------------|

| 1    | 1           | 1         | 5          |

| 2    | 1           | 2         | 7          |

| 3    | 3           | 2         | 2          |

| 4    | 5           | 3         | 3          |

| 5    | 5           | 3         | 4          |

| 6    | 5           | 6         | 4          |

+------+-------------+-----------+------------+

SELECT 6

Time: 0.007s

CompanyDatabase>



=>Adds a new employee to a department

CompanyDatabase> insert into employees(id,fullname,salary,position,phoneextension,isparttime,departmentid) values (11,’The Hulk’, 50000,'Software Developer',2

 85,false,5)

INSERT 0 1

Time: 0.013s

CompanyDatabase> select * from employees

+------+-----------------------------+------------+--------------------+------------------+--------------+---------------------+----------------+

| id   | fullname                    | salary     | position           | phoneextension   | isparttime   | parkingspotnumber   | departmentid   |

|------+-----------------------------+------------+--------------------+------------------+--------------+---------------------+----------------|

| 1    |Michael Tyson                | $90,093.89 | Software Engineer  | 211              | False        | <null>              | 5              |

| 2    | Mira Kang                   | $90,093.89 | Software Engineer  | 211              | False        | <null>              | 5              |

| 3    | Tatiana                     | $90,093.89 | Software Engineer  | 211              | False        | <null>              | 5              |

| 4    | Juanito                     | $90,093.89 | Software Engineer  | 211              | False        | <null>              | 5              |

| 5    | Goupo                    | $90,093.89 | Software Engineer  | 211              | False        | <null>              | 5              |

| 8    | Christen                       | $500.00    | Cook               | 201              | False        | <null>              | 1              |

| 9    | Maria                       | $500.00    | Cook               | 202              | False        | <null>              | 1              |

| 10   | Joselin                     | $500.00    | Cook               | 203              | False        | <null>              | 1              |

| 6    | Manny                       | $90,093.89 | Software Developer | 211              | False        | <null>              | 2              |

| 11   |The Hulk         | $90,093.89 | Software Developer | 285              | False        | <null>              | 5              |

+------+-----------------------------+------------+--------------------+------------------+--------------+---------------------+----------------+

SELECT 10

Time: 0.010s



=>Updating a employee's department

CompanyDatabase> update employees set departmentid=5, position ='Software Developer' where id = 8

UPDATE 1

Time: 0.034s

CompanyDatabase> select * from employees

+------+-----------------------------+------------+--------------------+------------------+--------------+---------------------+----------------+

| id   | fullname                    | salary     | position           | phoneextension   | isparttime   | parkingspotnumber   | departmentid   |

|------+-----------------------------+------------+--------------------+------------------+--------------+---------------------+----------------|

| 1    | Michael Tyson               | $90,093.89 | Software Engineer  | 211              | False        | <null>              | 5              |

| 2    | Mira Kang                   | $90,093.89 | Software Engineer  | 211              | False        | <null>              | 5              |

| 3    | Tatiana                     | $90,093.89 | Software Engineer  | 211              | False        | <null>              | 5              |

| 4    | Juanito                     | $90,093.89 | Software Engineer  | 211              | False        | <null>              | 5              |

| 5    | Charlie                     | $90,093.89 | Software Engineer  | 211              | False        | <null>              | 5              |

| 9    | Maria                       | $500.00    | Cook               | 202              | False        | <null>              | 1              |

| 10   | Joselin                     | $500.00    | Cook               | 203              | False        | <null>              | 1              |

| 6    | Manny                       | $90,093.89 | Software Developer | 211              | False        | <null>              | 2              |

| 11   | The Hulk                    | $90,093.89 | Software Developer | 285              | False        | <null>              | 5              |

| 8    | Carla                       | $500.00    | Software Developer | 201              | False        | <null>              | 5              |

+------+-----------------------------+------------+--------------------+------------------+--------------+---------------------+----------------+

SELECT 10

Time: 0.009s



=>Removing a product from an order

CompanyDatabase> select po.id,p.id, o.id, o.ordernumber, p.product_name, po.quantity from products as p join products_orders as po  on p.id = po.productid join orders a

 s o on po.orderid = o.id

+------+------+------+---------------+----------------+------------+

| id   | id   | id   | ordernumber   | product_name   | quantity   |

|------+------+------+---------------+----------------+------------|

| 1    | 1    | 1    | 321AL         | milk           | 5          |

| 2    | 1    | 2    | 325BL         | milk           | 7          |

| 3    | 3    | 2    | 325BL         | bread 16oz     | 2          |

| 4    | 5    | 3    | 225ZL         | sucar 8oz      | 3          |

| 5    | 5    | 3    | 225ZL         | sucar 8oz      | 4          |

| 6    | 5    | 6    | 246GL         | sucar 8oz      | 4          |

+------+------+------+---------------+----------------+------------+

SELECT 6

Time: 0.015s

CompanyDatabase> delete from products_orders where id=4

You're about to run a destructive command.

Do you want to proceed? (y/n): y

Your call!

DELETE 1

Time: 0.007s

CompanyDatabase> select po.id,p.id, o.id, o.ordernumber, p.product_name, po.quantity from products as p join products_orders as po  on p.id = po.productid join orders a

 s o on po.orderid = o.id

+------+------+------+---------------+----------------+------------+

| id   | id   | id   | ordernumber   | product_name   | quantity   |

|------+------+------+---------------+----------------+------------|

| 1    | 1    | 1    | 321AL         | milk           | 5          |

| 2    | 1    | 2    | 325BL         | milk           | 7          |

| 3    | 3    | 2    | 325BL         | bread 16oz     | 2          |

| 5    | 5    | 3    | 225ZL         | sucar 8oz      | 4          |

| 6    | 5    | 6    | 246GL         | sucar 8oz      | 4          |

+------+------+------+---------------+----------------+------------+

SELECT 5

Time: 0.020s
Time: 0.001s
companyDatabase>                                                                             

Time: 0.001s
  s o on po.orderid = o.id 
  
 +------+------+------+---------------+----------------+------------+ 
  
 | id   | id   | id   | ordernumber   | product_name   | quantity   | 
  
 |------+------+------+---------------+----------------+------------| 
  
 | 1    | 1    | 1    | 321AL         | milk           | 5          | 
  
 | 2    | 1    | 2    | 325BL         | milk           | 7          | 
  
 | 3    | 3    | 2    | 325BL         | bread 16oz     | 2          | 
  
 | 5    | 5    | 3    | 225ZL         | sucar 8oz      | 4          | 
  
 | 6    | 5    | 6    | 246GL         | sucar 8oz      | 4          | 
  
 +------+------+------+---------------+----------------+------------+ 
  
 SELECT 5 
  
 Time: 0.020s 
   employees.departmentid                                                                    
syntax error at or near "CREATE"
LINE 3: CREATE TABLE
        ^

Time: 0.068s
companyDatabase>                                                                             

Time: 0.000s
companyDatabase> select * from employee                                                      
+------+-------------+----------+------------+------------------+--------------+
| id   | full_name   | salary   | position   | phoneextention   | isparttime   |
|------+-------------+----------+------------+------------------+--------------|
| 1    | Gavin Stark | 42       | Janitor    | 123              | false        |
| 2    | MannyV      | 442      | cook       | 3423             | false        |
| 3    | MannyV      | 500      | cook       | 423              | false        |
| 4    | James       | 5010     | cook       | 4241             | true         |
+------+-------------+----------+------------+------------------+--------------+
SELECT 4
Time: 0.158s
companyDatabase> select 4                                                                    
+------------+
| ?column?   |
|------------|
| 4          |
+------------+
SELECT 1
Time: 0.014s
companyDatabase> CREATE TABLE Products(id SERIAL PRIMARY KEY, product_name v 
  archar(50), price MONEY);
