### ISSUE TITLE
Week 07 - Day 2 - Foreign Keys - The SQL

### ISSUE THREAD

**Issue by gstark** [evixamar/assignments#24]
As we continue to explore databases and ideas, this project will help you practice model databases and relationships, as well as help you get started on your capstone project.

First, you will expand your CompanyDatabase to have `Departments`, `Products` and `Orders`. You will be crafting queries for these new tables.

After that, this weekend is the next big push your final project, work on the HTML and CSS; As well as the database schema.

## Objectives

- Work with Foreign Keys
- Craft Queries

## Requirements

- Add a few tables and foreign keys to an existing database

### Explorer Mode

- [x] In your Company Database, add a table named:
  - C#: `Departments`. Give this table a few columns
  - Ruby: `departments`. Give this table a few columns
- [x] Add a Foreign key named:
  - C# `DepartmentId` to your `Employee` Table
  - Ruby: `department_id` to your `employees` table
- [x] Add tables named:
  - C#: `Products` and `Orders`. Give each table a few columns
  - Ruby: `products` and a `orders`. Give each table a few columns
- [x] In our company, 1 `Order` can have many `Products` and 1 `Product` can have many `Orders`. This will be a Many-to-Many relationship. Create the tables and foreign keys needed for this to happen

* [x] Create queries that can do the following:
  - [x] Given a department id, give me all employees in the department
  - [x] Given a department name, give me the phone extensions
  - [x] Find all orders that contain the product id of `2`
  - [x] Given an order id, display on the `OrderNumber`, and all the product names
  - [x] Inserts a new product
  - [x] Creates a new order
  - [x] Adds a product to an order
  - [x] Adds a new employee to a department
  - [x] Updating a employee's department
  - [x] Removing a product from an order

- [x] Turn in the above queries as a gist
- [ ] Work on your final project HTML. DO not sleep on this. You have the time and resources to get a good bit of this done this weekend.
- [ ] Complete your first draft of your database schema for your final project.

### Adventure Mode

- [ ] Give these [SQL Koans](https://sqlkoans.com/) a try.

### Epic Mode

- [ ] Investigate working with C#/Ruby and Postgres

## Additional Resources

- [PostgreSQL 10 Documentation](https://www.postgresql.org/docs/10/static/index.html)

## Recommended Practice:

- For more practice, Hackerrank has a [SQL Track](https://www.hackerrank.com/domains/sql)

**Comment by evixamar** [comment]
![Sql-1](https://user-images.githubusercontent.com/45954371/57095502-0e9b2200-6ce1-11e9-84ae-f32ac8391319.gif)
![Sql-Full](https://user-images.githubusercontent.com/45954371/57095525-21adf200-6ce1-11e9-8d6c-b3ef43abcca2.gif)
![SQL-4](https://user-images.githubusercontent.com/45954371/57095526-21adf200-6ce1-11e9-8dbd-2bbe4abc7cd0.gif)
![Sql-3](https://user-images.githubusercontent.com/45954371/57095527-21adf200-6ce1-11e9-84a2-8825e56e2c9f.gif)
![Sql-2](https://user-images.githubusercontent.com/45954371/57095528-21adf200-6ce1-11e9-8007-40f790a12f8b.gif)
![Sql-1](https://user-images.githubusercontent.com/45954371/57095529-22468880-6ce1-11e9-8028-e68d71b7daf4.gif)

**Comment by evixamar** [comment]
![Sql-Full](https://user-images.githubusercontent.com/45954371/57095264-71d88480-6ce0-11e9-8206-d149c70f2aab.gif)
![SQL-4](https://user-images.githubusercontent.com/45954371/57095265-71d88480-6ce0-11e9-9938-d9acfec9fc43.gif)
![Sql-3](https://user-images.githubusercontent.com/45954371/57095266-71d88480-6ce0-11e9-94ae-bf6517a00ec2.gif)
![Sql-2](https://user-images.githubusercontent.com/45954371/57095267-71d88480-6ce0-11e9-8515-e89b4d47ecfb.gif)
![Sql-1](https://user-images.githubusercontent.com/45954371/57095268-71d88480-6ce0-11e9-9511-3c28457c73e6.gif)
