### ISSUE TITLE
Week 01 - Day 4 - Mock Portoflio

### ISSUE THREAD

**Issue by mdewey** [evixamar/assignments#4]
# A Portfolio

For your first weekend project, we're going to be starting work on a portfolio website that you can improve over the rest of your career.

![Mockup](https://raw.githubusercontent.com/tiy-tpa-fee/assignments/master/portfolio/mockup.png)

You can find image assets you'll need here:

> https://github.com/tiy-tpa-fee/assignments/tree/master/portfolio/assets

The font used is [Roboto](https://fonts.google.com/specimen/Roboto).

Also, feel free to change it from Jason's picture to a picture of yourself.

## Objectives

- Build on your knowledge of HTML & CSS
- Implement, from scratch, a given design
- Use flexbox techniques layout pages.

## Requirements

- Initially, you should implement the design as close as possible to the mockup. Later, you might choose to fit your personality/style.

- **Note**: You should complete at least the tasks given for _explorer_ mode as listed below before turning in the assignment, as well as before attempting _adventure_ or _epic_ modes.

### Explorer Mode

- [x] Recreate the page as closely as you possibly can. Use the same fonts, sizes, and colors.
- [x] Make sure the site is responsive.
- [x] Deploy your site

### Adventure Mode

- [ ] Take the time to personalize the site with information about yourself, links to your projects, and your pictures.
- [ ] Keep it professional, but make it your own.

### Epic Mode
- [ ] Go back and work on the adventure or epic mode for a past assignment.
- [ ] Start to research [JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript)

**Comment by evixamar** [comment]
https://github.com/evixamar/mock-portfolio

Good morning, first and foremost, thank you for the kind words. I really struggled with this one over the weekend, I think I need to get the core foundation down and understanding how the lay out, design and CSS works, I'm truly willing to do the work, I just am having a hard time grasping it. Any help would greatly be appreciated

**Comment by mdewey** [comment]
Manny! 

I know CSS might be rough, but make sure you have committed all your code to GitHub so I can check it out and please come see if you have any questions!

I am going to re-open this issue so you can put your latest code on GitHub.

**Comment by evixamar** [comment]
https://github.com/evixamar/mock-portfolio
Hi Mark, please confirm that this one went through......

This one is the minesweep that is showing as one that was not sent... 
 https://github.com/evixamar/minesweep.git

**Comment by mdewey** [comment]
A couple of things:

1) It looks like its not the latest commit, be sure to push all of your code up
2) I see your deployed version and it not complete enough to be acceptable. If you can 
 - [ ] get the layout in the right order to the original
 - [ ] get the background images correct 
 - [ ] Get some items flexed (like the projects) 

3) The minesweeper project should be submitted to the minesweeper issue, not this issue.

**Comment by evixamar** [comment]
https://github.com/evixamar/mock-portfolio

Hi Mark,  Please review and advise if I need to make any updates. Looking at the site i would like to make it a bit more stable, but either way please advise...

**Comment by evixamar** [comment]
Mark, 
Below you will find the Mock Portfolio. 
Please let me know if you have any questions. thanks

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBWZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--19d6199fa14f30b194db6d85ef06369fdd985597/giphy-10.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/75)**__
